name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build
        run: |
          sudo apt update -y
          # sudo apt install -y build-essential git python3
          sudo apt install -y make gcc git python3
          git clone --single-branch --depth=1 --recurse-submodules https://github.com/CoreELEC/CoreELEC
          cd CoreELEC
          DEVICE=Amlogic-no ARCH=aarch64 make
          
